"""initial_schema

Revision ID: ccf1187cd090
Revises: 
Create Date: 2026-03-07 12:08:37.512219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf1187cd090'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('monitor_days_quente', sa.Integer(), nullable=False),
    sa.Column('monitor_days_morno', sa.Integer(), nullable=False),
    sa.Column('monitor_days_frio', sa.Integer(), nullable=False),
    sa.Column('collect_hour', sa.Integer(), nullable=False),
    sa.Column('max_leads_per_day', sa.Integer(), nullable=False),
    sa.Column('instagram_enabled', sa.Boolean(), nullable=False),
    sa.Column('youtube_enabled', sa.Boolean(), nullable=False),
    sa.Column('facebook_enrichment', sa.Boolean(), nullable=False),
    sa.Column('linkedin_enrichment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', name='leadplatform'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('birthdate_source', sa.String(length=50), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('is_business_account', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_engagement', sa.Integer(), nullable=False),
    sa.Column('score_intention', sa.Integer(), nullable=False),
    sa.Column('score_profile', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('QUENTE', 'MORNO', 'FRIO', 'DESCARTE', name='leadcategory'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ENRICHING', 'MONITORING', 'READY', 'CONTACTED', 'ARCHIVED', name='leadstatus'), nullable=False),
    sa.Column('monitor_until', sa.DateTime(), nullable=True),
    sa.Column('monitoring_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_monitored_at', sa.DateTime(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_username'), 'leads', ['username'], unique=False)
    op.create_table('search_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('leads_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_table('search_jobs')
    op.drop_index(op.f('ix_leads_username'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
